In [2]:
import numpy as np

In [19]:
y1 = np.array([[5, 5, 1, 6, 5],
       [7, 7, 8, 9, 6],
       [1, 7, 2, 4, 5],
       [3, 4, 7, 0, 8],
       [1, 8, 2, 0, 2]])


yy1 = np.copy(y1)

print( np.version.version)

1.18.5


In [20]:
print( 2*yy1[::2, :] )

# 2. Multipliez une ligne sur 2
# On assigne les lignes modifiées à la matrice qui par référence changera les lignes
yy1[::2, :] = 2*yy1[::2, :]

[[10 10  2 12 10]
 [ 2 14  4  8 10]
 [ 2 16  4  0  4]]


In [21]:
yy1

array([[10, 10,  2, 12, 10],
       [ 7,  7,  8,  9,  6],
       [ 2, 14,  4,  8, 10],
       [ 3,  4,  7,  0,  8],
       [ 2, 16,  4,  0,  4]])

In [22]:
# 3. Multipliez une ligne sur trois
yy1[::3, :] = 3*yy1[::3, :]

In [24]:
yy1

array([[30, 30,  6, 36, 30],
       [ 7,  7,  8,  9,  6],
       [ 2, 14,  4,  8, 10],
       [ 9, 12, 21,  0, 24],
       [ 2, 16,  4,  0,  4]])

In [29]:
# 4. ajoutez 100
yy1[:, -1]  = yy1[:, -1] + 100

print(yy1)

[[ 30  30   6  36 330]
 [  7   7   8   9 306]
 [  2  14   4   8 310]
 [  9  12  21   0 324]
 [  2  16   4   0 304]]


In [68]:
y2 = np.array([[[89, 26, 78, 55, 23],
        [32, 92, 86, 55, 27],
        [87, 46, 63, 43, 77],
        [27, 18, 15, 20, 65],
        [52, 75, 82,  9, 38]],

       [[78, 20, 86, 16, 31],
        [46,  3, 59,  6, 50],
        [76, 73, 41, 66, 42],
        [70, 80, 62, 58, 41],
        [41, 65, 49,  0, 79]],

       [[13,  9, 58, 35, 32],
        [80, 86, 30, 73, 18],
        [52, 73, 74,  8, 40],
        [80, 27, 26, 94,  8],
        [30, 62,  3, 35, 75]],

       [[69, 54, 24, 28, 44],
        [29, 85, 56,  7, 69],
        [13,  1, 62, 10, 66],
        [ 6,  5, 31, 78, 92],
        [11, 41, 38,  4, 67]],

       [[30, 91, 12, 10, 91],
        [65, 95, 36, 54, 35],
        [49, 96, 21,  5, 87],
        [68, 82, 90, 36, 56],
        [41, 18, 75, 39, 99]]])


yy2 = np.copy(y2)

In [69]:
# 4. Pour chaque "numéro" de matrice paire et chaque ligne paire multipliez par 2 les valeurs
yy2[::2, ::2] = 2*yy2[::2, ::2] 

In [70]:
yy2

print(178+  52+ 156+110+  46)

542


In [71]:
# 5. Pour chaque matrice dont la somme des valeurs de la ligne est impaire, 
# ajoutez 100 à toutes les valeurs de cette ligne.

In [72]:
mask = y2.sum(0).sum(1)  % 2 == 1

mask

array([False, False,  True,  True, False])

In [82]:

# sum(2) somme des lignes de chaque matrice en dimension 3D
print( yy2.sum(2))

print(yy2.sum(2).sum(1))
print(542 + 292 + 632 + 145 + 512)

[[542 292 632 145 512]
 [231 164 298 311 234]
 [294 287 494 235 410]
 [219 246 152 212 161]
 [468 285 516 332 544]]
[2123 1238 1720  990 2145]
2123


In [90]:
print( yy2.sum(2) )

print(yy2[0].sum(1))

[[542 292 632 145 512]
 [231 164 298 311 234]
 [294 287 494 235 410]
 [219 246 152 212 161]
 [468 285 516 332 544]]
[542 292 632 145 512]


In [109]:
mask = yy2.sum(2).sum(1) % 2 == 1
print(mask)

[ True False False False  True]


In [98]:
yy2[mask]

array([[[178,  52, 156, 110,  46],
        [ 32,  92,  86,  55,  27],
        [174,  92, 126,  86, 154],
        [ 27,  18,  15,  20,  65],
        [104, 150, 164,  18,  76]],

       [[ 60, 182,  24,  20, 182],
        [ 65,  95,  36,  54,  35],
        [ 98, 192,  42,  10, 174],
        [ 68,  82,  90,  36,  56],
        [ 82,  36, 150,  78, 198]]])

In [110]:
yy3 = np.random.randint(100, 500, size=(10, 10))

In [111]:
yy3

array([[482, 354, 275, 368, 471, 485, 143, 474, 317, 164],
       [195, 213, 277, 350, 133, 291, 233, 219, 483, 393],
       [251, 216, 100, 497, 315, 405, 275, 347, 143, 407],
       [121, 199, 228, 116, 135, 265, 232, 332, 267, 153],
       [250, 101, 469, 461, 461, 474, 277, 107, 245, 215],
       [142, 291, 297, 420, 304, 196, 146, 414, 156, 236],
       [188, 100, 237, 458, 488, 153, 414, 282, 211, 185],
       [306, 443, 349, 483, 480, 354, 253, 354, 362, 456],
       [311, 122, 310, 231, 152, 136, 379, 394, 499, 102],
       [276, 375, 335, 293, 309, 172, 343, 271, 132, 266]])

1 Créez un mask qui permet d'extraire les lignes dont la somme des valeurs est paire.

In [114]:
mask = yy3.sum(1) % 2 == 0

print(mask)

[False False  True  True  True  True  True  True  True  True]


In [115]:
yy3[mask]

array([[251, 216, 100, 497, 315, 405, 275, 347, 143, 407],
       [121, 199, 228, 116, 135, 265, 232, 332, 267, 153],
       [250, 101, 469, 461, 461, 474, 277, 107, 245, 215],
       [142, 291, 297, 420, 304, 196, 146, 414, 156, 236],
       [188, 100, 237, 458, 488, 153, 414, 282, 211, 185],
       [306, 443, 349, 483, 480, 354, 253, 354, 362, 456],
       [311, 122, 310, 231, 152, 136, 379, 394, 499, 102],
       [276, 375, 335, 293, 309, 172, 343, 271, 132, 266]])