In [10]:
import numpy as np

In [3]:
print(np)

<module 'numpy' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>


In [11]:
print(np.sctypes)

{'int': [<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.int64'>], 'uint': [<class 'numpy.uint8'>, <class 'numpy.uint16'>, <class 'numpy.uint32'>, <class 'numpy.uint64'>], 'float': [<class 'numpy.float16'>, <class 'numpy.float32'>, <class 'numpy.float64'>, <class 'numpy.float128'>], 'complex': [<class 'numpy.complex64'>, <class 'numpy.complex128'>, <class 'numpy.complex256'>], 'others': [<class 'bool'>, <class 'object'>, <class 'bytes'>, <class 'str'>, <class 'numpy.void'>]}


In [14]:
n = np.array([1, 2, np.nan])

In [16]:
n.dtype

dtype('float64')

In [25]:
m = np.array(["Big data blabla", "Python", "Pandas"], dtype='<U8')

In [26]:
m.dtype

dtype('<U8')

In [27]:
m

array(['Big data', 'Python', 'Pandas'], dtype='<U8')

In [28]:

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
x = np.full((2,3), 4.5)

In [34]:
x[0][0] = 9
x[0,1] = 100
print(x)

[[  9.  100.    4.5]
 [  4.5   4.5   4.5]]


In [38]:
x = np.random.randint(100, size=(2,3))

print(x)

[[44 99 29]
 [26 83  4]]


In [40]:
x.dtype

dtype('int64')

In [46]:
x[0,0] = 1.2
print(x)

[[ 1 99 29]
 [26 83  4]]


In [48]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

a[:, 1]

array([2, 5, 8])

In [50]:
a = np.array([
       [[10, 11, 12], [13, 14, 15], [16, 17, 18]], # matrix 0
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]
])

In [53]:
a[0]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

1. Récupérez 23,24, 25

In [59]:
a[1, 1, :]

array([23, 24, 25])

In [61]:
# 13 23 33
a[:,1,0]

array([13, 23, 33])

In [81]:
# 11 21 31
x, y, z = a.shape
# 0 0 0
# 1 1 0
# 2 2 0
for i in range(x):
    print(i, i, 0)
    print(a[i, i, 0])
    
print( a[:, : , 0].diagonal() )




0 0 0
10
1 1 0
23
2 2 0
36
[10 23 36]


In [83]:
a.sum(0)

array([[60, 63, 66],
       [69, 72, 75],
       [78, 81, 84]])

1. Vérifiez à l'aide d'un calcul que l'on a bien la somme des matrice avec sum(0)

In [96]:
for i in range(x):
    print(a[i])
    
for l in a[:, 0, :].T:
    print(sum(l ))
    

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[20 21 22]
 [23 24 25]
 [26 27 28]]
[[30 31 32]
 [33 34 35]
 [36 37 38]]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices